# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=200)),
                ('dnsname', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=200)),
                ('os_ver', models.CharField(max_length=200)),
                ('os_sp', models.CharField(max_length=200)),
                ('sid', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='path',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='sid',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spn',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Person'),
        ),
    ]
