# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170918_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='sid',
            field=models.CharField(max_length=100),
        ),
    ]
