# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20170919_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='workstation',
            options={'verbose_name': 'Workstation', 'verbose_name_plural': 'Workstations'},
        ),
        migrations.RemoveField(
            model_name='workstation',
            name='location',
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=400, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=200, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='countrycode',
            field=models.CharField(max_length=5, verbose_name='Countrycode'),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(max_length=200, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='employee',
            field=models.CharField(max_length=50, verbose_name='Employee No.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fax',
            field=models.CharField(max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(max_length=200, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(max_length=50, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='path',
            field=models.CharField(max_length=400, verbose_name='LDAP-Path'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sid',
            field=models.CharField(max_length=100, verbose_name='SID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='person',
            name='userid',
            field=models.CharField(max_length=50, verbose_name='User-ID'),
        ),
    ]
