# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20170919_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ('name',), 'verbose_name': 'Workstation', 'verbose_name_plural': 'Workstations'},
        ),
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='person',
            name='lockout',
            field=models.BooleanField(default=True, verbose_name='User Lockout'),
        ),
        migrations.AddField(
            model_name='person',
            name='pwep',
            field=models.BooleanField(default=True, verbose_name='PW expired'),
        ),
        migrations.AddField(
            model_name='person',
            name='pwne',
            field=models.BooleanField(default=True, verbose_name='PW never expires'),
        ),
        migrations.AddField(
            model_name='person',
            name='pwno',
            field=models.BooleanField(default=True, verbose_name='PW Read Only'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='dnsname',
            field=models.CharField(max_length=200, verbose_name='DNS Name'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Computer Name'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='os',
            field=models.CharField(max_length=200, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='os_sp',
            field=models.CharField(max_length=200, verbose_name='OS Service Pack'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='os_ver',
            field=models.CharField(max_length=200, verbose_name='OS Version'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='path',
            field=models.CharField(max_length=400, verbose_name='LDAP-Path'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='sid',
            field=models.CharField(max_length=100, verbose_name='SID'),
        ),
    ]
