# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20170921_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pwno',
        ),
    ]
