# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_remove_person_pwno'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='zipcode',
            field=models.CharField(default='51373', max_length=400, verbose_name='Address'),
        ),
    ]
