# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_person_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pwne',
        ),
        migrations.AddField(
            model_name='person',
            name='pwex',
            field=models.BooleanField(default=True, verbose_name='PW Expires'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
    ]
