# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20170921_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Software Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('workstations', models.ManyToManyField(to='cmdb.Workstation')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
            },
        ),
    ]
