# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_software'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerCateogry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('token', models.CharField(max_length=3, verbose_name='Category Token')),
            ],
        ),
    ]
