# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_computercateogry'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ComputerCateogry'),
        ),
    ]
