# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_auto_20170921_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Location Name')),
                ('token', models.CharField(max_length=3, verbose_name='Location Token')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.AlterModelOptions(
            name='computercategory',
            options={'verbose_name': 'Computer Category', 'verbose_name_plural': 'Computer Categories'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='zipcode',
        ),
    ]
