# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_auto_20170922_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Office', 'verbose_name_plural': 'Offices'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='countrycode',
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(max_length=200, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='employee',
            field=models.CharField(max_length=50, null=True, verbose_name='Employee No.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fax',
            field=models.CharField(max_length=50, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(max_length=200, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(max_length=50, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='person',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Location', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='os',
            field=models.CharField(max_length=200, null=True, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='os_sp',
            field=models.CharField(max_length=200, null=True, verbose_name='OS Service Pack'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='os_ver',
            field=models.CharField(max_length=200, null=True, verbose_name='OS Version'),
        ),
    ]
