# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_auto_20170922_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=400, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=200, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=models.CharField(max_length=15, null=True, verbose_name='ZIP'),
        ),
    ]
