# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0018_auto_20170922_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='nation',
            new_name='country',
        ),
    ]
